### ISSUE TITLE
Crash on fullscreen

### ISSUE THREAD

**Issue by Satur0x** [ashpynov/PlayniteSound#7]
First of all thanks for the amazing mod, just wanted to make a note of a bug that happened with the latest update.
Changing playnite from windowed to fullscreen mode (both with the playnite feature and the normal fullscreen desktop mode) causes playnite to crash. Switching to fullscreen mode reveals that the crash is caused by PlayniteSoundMod

**Comment by nikolay-borzov** [comment]
I've got crash on Playnite start
```
ERROR|ExtensionFactory:Failed to execute OnGameSelected method from Playnite Sounds Mod plugin.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PlayniteSounds.PlayniteSounds.PlayMusicFromFiles(String[] musicFiles)
   at PlayniteSounds.PlayniteSounds.PlayMusicFromFirst(IEnumerable`1 games)
   at PlayniteSounds.PlayniteSounds.PlayMusicBasedOnSelected()
   at PlayniteSounds.PlayniteSounds.OnGameSelected(OnGameSelectedEventArgs args)
   at Playnite.Plugins.ExtensionFactory.InvokeOnGameSelected(List`1 oldValue, List`1 newValue) in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 725
```

**Comment by ashpynov** [comment]
Please check on version v.5.7.9

**Comment by nikolay-borzov** [comment]
Fixed for me! Thanks!
